### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by ancasimon** [nss-evening-cohort-11/bands-battleheart#1]
## User Story
As a Battleheart fan, I should be able to see the logo at the top of the home page and access information about the band, their fan club, their albums, their tour dates, and their merchandise.

## AC
WHEN I go to any page on their website,
THEN I can see the logo of the band at the top of the page, and 
THEN I can click any of these buttons to access the other pages: Home, Bio, Fans, Dates, Discography, and Merch,
AND the corresponding page will open. 

## Dev Notes
* Wrap navbar in a container.
* Use a Bootstrap navbar.
* Provide the links to the other html pages.

**Comment by kenymc1** [comment]
<img width="1102" alt="Screen Shot 2020-02-05 at 7 55 11 PM" src="https://user-images.githubusercontent.com/50973891/73899271-c0a7e180-4851-11ea-83c2-70870c310836.png">
