### ISSUE TITLE
Fans page

### ISSUE THREAD

**Issue by ancasimon** [nss-evening-cohort-11/bands-battleheart#10]
## User Story
As a user, I want to access information about the band's fan club. 

## AC
WHEN I go to the band's website,
THEN I can click a navbar menu labeled Fans,
AND the Fans page opens, 
AND I can see an overview of the fan club's activities, 
AND I can see a (currently static) button about joining the fan club. 

## Dev Notes
* In the fans.html file, create a div container that includes an h1 tag for the fan club's name, a paragraph for the fan club description, and a button labeled Join.

**Comment by kenymc1** [comment]
![battle heart](https://user-images.githubusercontent.com/50973891/74201222-bf4e2e80-4c2e-11ea-9550-c2ff418a1ad4.png)
