### ISSUE TITLE
Buy Album

### ISSUE THREAD

**Issue by ancasimon** [nss-evening-cohort-11/bands-battleheart#12]
## User Story
As a user, when I go to the band's website, I am quickly able to access the Discography page. 

## AC
WHEN I go to the band's home page, 
THEN I can see a button labeled Buy Album,
AND when I click on the button, the browser automatically opens the Discography.

## Dev Notes
* Bootstrap button. 
* Button label: Buy Album
* Button has a link to the Discography page.

**Comment by ancasimon** [comment]
See the Buy Album button below:

![home](https://user-images.githubusercontent.com/50973891/74201190-a180c980-4c2e-11ea-92cc-5d73f0156a4f.png)

**Comment by kenymc1** [comment]
Done!!
