### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by ancasimon** [nss-evening-cohort-11/bands-battleheart#3]
## User Story
As a Battleheart fan, I want to see information about contacting the band, and I want to easily access the social media pages for the band: Facebook, Instagram, Twitter, YouTube, Spotify, iTunes, Pandora. 

## AC
WHEN I scroll to the bottom of the page, 
THEN I can see information about contacting the band (phone number, mailing address, email address),
AND I can click on the email address link to open an email message, 
AND I can see the following social media icons: Facebook, Instagram, Twitter, YouTube, Spotify, iTunes, Pandora,
AND I can click each one to open a relevant site about the band, 
AND I can click on each social media icon to open the corresponding site in a separate window. 

## Dev Notes
* div container for the footer. 
* Use Bootstrap footer. 
* Display all icons in the footer of the pages. 
* Use FontAwesome icons.

**Comment by kenymc1** [comment]
<img width="1110" alt="Screen Shot 2020-02-05 at 7 55 33 PM" src="https://user-images.githubusercontent.com/50973891/73899254-abcb4e00-4851-11ea-9189-3c52b938cfde.png">
