### ISSUE TITLE
Tour cards

### ISSUE THREAD

**Issue by ancasimon** [nss-evening-cohort-11/bands-battleheart#5]
## User Story
As a Battleheart fan, I want to see information about their upcoming tour band performances with date, city, state, venue, and a link to purchase tickets. 

## AC
WHEN I go to the Tour page, 
THEN I can see tour dates, times, venues, cities, states, and buttons for buying tickets,
AND I can click the buttons to buy tickets to access Ticketmaster. 

## Dev Notes
* Create array of objects with the following key-value pairs: date, time, venue, city, state. 
*  Write a `printToDom` function. 
* Write the `tourCards` function that builds the `domString` and prints the cards to the page. 
* The function also adds the button to purchase tickets to the `domString`.  
* The function calls the `printToDom` function.  
* Add a div container with the id="ticketContainer" in the tour.html file. 
* Write the init function and include the `tourCards` function in it and then call it.

**Comment by ancasimon** [comment]
```
const printToDom = (divId, textToPrint) => {
    const selectedDiv = document.getElementById(divId);
    selectedDiv.innerHTML = textToPrint;
};
```

**Comment by kenymc1** [comment]
![tour dates](https://user-images.githubusercontent.com/50973891/74204893-a9466b00-4c3a-11ea-8fd2-787b532e2de6.png)
