### ISSUE TITLE
Discography cards

### ISSUE THREAD

**Issue by ancasimon** [nss-evening-cohort-11/bands-battleheart#6]
## User Story
As a user, when the page loads, I should see multiple cards with album information.

## AC
WHEN I access the page, 
THEN I see 6 album cards
AND each album card contains album picture, title, release year, and  song list (which displays when user hovers on the album card).

## Dev Notes
* Create an array of objects with the following key-value pairs: image, title, release year, an array of the album songs, and a "sku" number for the album. 
*  Write a `printToDom` function. 
* Write the `albumCards` function that builds the `domString` and prints the cards to the page. 
* The function calls the `printToDom` function.  
* Add a div container with the id="albumContainer" in the discography.html file. 
* Write the init function and include the `albumCards` function in it and then call it. 
* Add eventListener that listens for the hover on any card, which triggers the secondary loop in order to display each album's songs. (use getElementsbyClassName and loop over the album cards to attach the event listener to each one)

**Comment by davideverett89** [comment]
![image](https://user-images.githubusercontent.com/59631645/74122625-890ea180-4b91-11ea-9bf4-63bc2cff1d41.png)
