### ISSUE TITLE
Form to join newsletter

### ISSUE THREAD

**Issue by ancasimon** [nss-evening-cohort-11/bands-battleheart#8]
## User Story
As a user, when I go to the website, I can find a section where I can sign up for the band's newsletter.

## AC
WHEN I click the Become a Fan button on the home page or the Join button on the Fans page,
THEN a form appears where I can enter my information,
AND I can submit the form,
AND I get an alert that confirms my subscription.

## Dev Notes
* Bootstrap form that is a single row takes up the whole screen. 
* There is a header labeled: "Join the Band" - all in caps. 
* There is an overview paragraph. 
* Form includes the following fields: Name, Email, Address, City, State, Zip, and the Sign in button. 
* Bootstrap button for the Submit button.
* Each field needs its own unique ID. 
* Assign a class to the form. 
* Assign a unique ID to the button. 
* Add an alert that pops up once the user submits their information.

**Comment by kenymc1** [comment]
<img width="715" alt="Screen Shot 2020-02-10 at 7 32 56 PM" src="https://user-images.githubusercontent.com/50973891/74205274-4b1a8780-4c3c-11ea-9346-eb0607d2c642.png">

**Comment by kenymc1** [comment]
From Bootstrap

<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Password</label>
      <input type="password" class="form-control" id="inputPassword4">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">City</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        <option>...</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>

**Comment by kenymc1** [comment]
https://getbootstrap.com/docs/4.4/components/forms/

**Comment by kenymc1** [comment]
<img width="710" alt="Screen Shot 2020-02-10 at 7 41 08 PM" src="https://user-images.githubusercontent.com/50973891/74205556-7f427800-4c3d-11ea-824d-4c9f742e949f.png">

**Comment by kenymc1** [comment]
<img width="714" alt="Screen Shot 2020-02-10 at 7 43 30 PM" src="https://user-images.githubusercontent.com/50973891/74205597-a8fb9f00-4c3d-11ea-9001-f19aabd3fbe7.png">
