### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by ancasimon** [nss-evening-cohort-11/bands-battleheart#9]
## User Story
As a user, when I access the band's web site, this is the first page I see. 

## AC
WHEN I go to the band's main page,
THEN I can see a large picture of the band on top of a darker background,
AND I can see a button to subscribe to the newsletter. 

## Dev Notes
* Bootstrap jumbotron for the picture. 
* Bootstrap button.

**Comment by kenymc1** [comment]
![home](https://user-images.githubusercontent.com/50973891/74201190-a180c980-4c2e-11ea-92cc-5d73f0156a4f.png)
